#ifndef CFI_METADATA_DEFINITIONS_H
#define CFI_METADATA_DEFINITIONS_H

#define CFI_MD_SECTION_PREFIX ".sce_debug"
#define CFI_MD_MAGIC_START 0xdeadbeef

enum CFI_MD_TYPE {
  FUNC_START = 1,
  FUNC_END,
  DEFINITE_CALL,
  FUNC_RETURN,
  CALL_PATCH,
  ICALL_PATCH,
  STATE_UPDATE,
  STATE_PATCH,
  BRANCH_OVER_PATCH,
  CFI_CHECK,
  BRANCH,
  COND_BRANCH,
  MBB_STATISTIC,
  PREDECESSOR,
};

#endif
